from app.config import use_local_store

if use_local_store():
    from app.sqlite_store import (  # noqa: F401
        DEFAULT_BIDER,
        DEFAULT_CONTROL,
        active_job_count,
        add_event,
        delete_source,
        find_job,
        get_bider_settings,
        get_control,
        get_job,
        get_source,
        insert_job,
        insert_source,
        job_counts_by_source,
        job_counts_since_by_source,
        list_jobs,
        list_sources,
        now_iso,
        queued_jobs,
        update_bider_settings,
        update_control,
        update_job,
        update_source,
    )
else:
    from app.supabase_store import (  # noqa: F401
        DEFAULT_BIDER,
        DEFAULT_CONTROL,
        active_job_count,
        add_event,
        delete_source,
        find_job,
        get_bider_settings,
        get_control,
        get_job,
        get_source,
        insert_job,
        insert_source,
        job_counts_by_source,
        job_counts_since_by_source,
        list_jobs,
        list_sources,
        now_iso,
        queued_jobs,
        update_bider_settings,
        update_control,
        update_job,
        update_source,
    )
